"use client";

import React from "react";
import { EvaluationResult } from "@/types";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { Badge } from "@/components/ui/badge";
import {
  Trophy,
  Code2,
  MessageSquare,
  BrainCircuit,
  CheckCircle2,
  AlertTriangle,
  Lightbulb,
  Award,
} from "lucide-react";

interface ScoreCardProps {
  evaluation: EvaluationResult;
}

export const ScoreCard: React.FC<ScoreCardProps> = ({ evaluation }) => {
  const getScoreColor = (score: number) => {
    if (score >= 85) return { text: "text-emerald-400", border: "border-emerald-500/30", bg: "bg-emerald-950/40", bar: "bg-gradient-to-r from-emerald-500 to-teal-400" };
    if (score >= 70) return { text: "text-cyan-400", border: "border-cyan-500/30", bg: "bg-cyan-950/40", bar: "bg-gradient-to-r from-blue-500 to-cyan-400" };
    if (score >= 50) return { text: "text-amber-400", border: "border-amber-500/30", bg: "bg-amber-950/40", bar: "bg-gradient-to-r from-amber-500 to-yellow-400" };
    return { text: "text-rose-400", border: "border-rose-500/30", bg: "bg-rose-950/40", bar: "bg-gradient-to-r from-rose-500 to-red-400" };
  };

  const overallStyle = getScoreColor(evaluation.overallScore);

  return (
    <div className="flex flex-col gap-8 w-full max-w-5xl mx-auto">
      {/* Top Banner: Overall Score Circle & Executive Summary */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        {/* Overall Score Circle Card */}
        <Card className={`md:col-span-1 flex flex-col items-center justify-center text-center relative overflow-hidden ${overallStyle.bg} ${overallStyle.border}`}>
          <div className="absolute top-0 right-0 p-24 bg-cyan-500/10 blur-2xl rounded-full pointer-events-none" />
          <Award className={`h-10 w-10 ${overallStyle.text} mb-3`} />
          <CardTitle className="text-lg text-slate-300 font-medium">Overall Score</CardTitle>
          
          <div className="relative my-4 flex items-center justify-center">
            {/* SVG Circular Progress Ring */}
            <svg className="w-36 h-36 transform -rotate-90">
              <circle
                cx="72"
                cy="72"
                r="60"
                stroke="currentColor"
                strokeWidth="10"
                className="text-slate-800"
                fill="transparent"
              />
              <circle
                cx="72"
                cy="72"
                r="60"
                stroke="currentColor"
                strokeWidth="10"
                strokeDasharray={377}
                strokeDashoffset={377 - (377 * evaluation.overallScore) / 100}
                strokeLinecap="round"
                className={`${overallStyle.text} transition-all duration-1000 ease-out`}
                fill="transparent"
              />
            </svg>
            <div className="absolute flex flex-col items-center">
              <span className={`text-4xl font-extrabold ${overallStyle.text}`}>
                {evaluation.overallScore}
              </span>
              <span className="text-xs text-slate-400 font-semibold uppercase tracking-wider">/ 100</span>
            </div>
          </div>

          <Badge
            variant={
              evaluation.overallScore >= 85
                ? "success"
                : evaluation.overallScore >= 66
                ? "indigo"
                : evaluation.overallScore >= 46
                ? "warning"
                : "destructive"
            }
            className="mt-1"
          >
            {evaluation.overallScore >= 85
              ? "Strong Hire Candidate"
              : evaluation.overallScore >= 66
              ? "Hire Candidate"
              : evaluation.overallScore >= 46
              ? "Needs Technical Polish"
              : "Below Technical Bar / Fail"}
          </Badge>
        </Card>

        {/* Executive Summary Feedback */}
        <Card className="md:col-span-2 flex flex-col justify-between">
          <CardHeader>
            <div className="flex items-center gap-2">
              <Trophy className="h-5 w-5 text-amber-400" />
              <CardTitle>Executive Interview Evaluation</CardTitle>
            </div>
            <CardDescription>Generated by Google Gemini 2.5 Intelligence</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <p className="text-slate-300 text-sm leading-relaxed bg-slate-950/50 border border-slate-800/80 p-4 rounded-xl">
              {evaluation.summaryFeedback}
            </p>

            <div className="space-y-2">
              <h5 className="text-xs font-bold uppercase tracking-wider text-slate-400 flex items-center gap-1.5">
                <Lightbulb className="h-4 w-4 text-cyan-400" /> Key Actionable Takeaways
              </h5>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                {evaluation.keyTakeaways.map((takeaway, idx) => (
                  <div
                    key={idx}
                    className="text-xs text-slate-300 p-2.5 rounded-lg bg-slate-800/60 border border-slate-700/50 flex items-start gap-2"
                  >
                    <span className="text-cyan-400 font-bold">•</span>
                    <span>{takeaway}</span>
                  </div>
                ))}
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Metric Score Breakdown Cards */}
      <Card>
        <CardHeader>
          <CardTitle className="text-lg">Category Performance Breakdown</CardTitle>
          <CardDescription>Detailed evaluation across primary interview dimensions</CardDescription>
        </CardHeader>
        <CardContent className="space-y-6">
          {/* Technical Knowledge Score */}
          <div className="space-y-2">
            <div className="flex items-center justify-between text-sm">
              <div className="flex items-center gap-2">
                <div className="p-2 rounded-lg bg-cyan-950/80 text-cyan-400 border border-cyan-500/20">
                  <Code2 className="h-4 w-4" />
                </div>
                <span className="font-semibold text-slate-200">Technical Knowledge & Depth</span>
              </div>
              <span className="font-bold text-cyan-400">{evaluation.technicalScore} / 100</span>
            </div>
            <Progress value={evaluation.technicalScore} indicatorColor={getScoreColor(evaluation.technicalScore).bar} />
          </div>

          {/* Communication Score */}
          <div className="space-y-2">
            <div className="flex items-center justify-between text-sm">
              <div className="flex items-center gap-2">
                <div className="p-2 rounded-lg bg-sky-950/80 text-sky-400 border border-sky-500/20">
                  <MessageSquare className="h-4 w-4" />
                </div>
                <span className="font-semibold text-slate-200">Communication & Structure</span>
              </div>
              <span className="font-bold text-sky-400">{evaluation.communicationScore} / 100</span>
            </div>
            <Progress value={evaluation.communicationScore} indicatorColor={getScoreColor(evaluation.communicationScore).bar} />
          </div>

          {/* Problem Solving Score */}
          <div className="space-y-2">
            <div className="flex items-center justify-between text-sm">
              <div className="flex items-center gap-2">
                <div className="p-2 rounded-lg bg-emerald-950/80 text-emerald-400 border border-emerald-500/20">
                  <BrainCircuit className="h-4 w-4" />
                </div>
                <span className="font-semibold text-slate-200">Problem Solving & Architecture</span>
              </div>
              <span className="font-bold text-emerald-400">{evaluation.problemSolvingScore} / 100</span>
            </div>
            <Progress value={evaluation.problemSolvingScore} indicatorColor={getScoreColor(evaluation.problemSolvingScore).bar} />
          </div>
        </CardContent>
      </Card>

      {/* Key Strengths & Areas for Improvement Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Key Strengths (Green accents) */}
        <Card className="border-emerald-500/30 bg-emerald-950/10">
          <CardHeader>
            <div className="flex items-center gap-2">
              <CheckCircle2 className="h-5 w-5 text-emerald-400" />
              <CardTitle className="text-emerald-300 text-lg">Key Strengths</CardTitle>
            </div>
          </CardHeader>
          <CardContent>
            <ul className="space-y-3">
              {evaluation.strengths.map((strength, index) => (
                <li key={index} className="flex items-start gap-3 text-sm text-slate-300">
                  <span className="flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-emerald-950 text-emerald-400 text-xs font-bold border border-emerald-500/30 mt-0.5">
                    ✓
                  </span>
                  <span>{strength}</span>
                </li>
              ))}
            </ul>
          </CardContent>
        </Card>

        {/* Areas for Improvement (Amber/Red accents) */}
        <Card className="border-amber-500/30 bg-amber-950/10">
          <CardHeader>
            <div className="flex items-center gap-2">
              <AlertTriangle className="h-5 w-5 text-amber-400" />
              <CardTitle className="text-amber-300 text-lg">Areas for Improvement</CardTitle>
            </div>
          </CardHeader>
          <CardContent>
            <ul className="space-y-3">
              {evaluation.areasForImprovement.map((area, index) => (
                <li key={index} className="flex items-start gap-3 text-sm text-slate-300">
                  <span className="flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-amber-950 text-amber-400 text-xs font-bold border border-amber-500/30 mt-0.5">
                    !
                  </span>
                  <span>{area}</span>
                </li>
              ))}
            </ul>
          </CardContent>
        </Card>
      </div>
    </div>
  );
};
